name: 'CLA Assistant'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: 'CLA Assistant'
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/blob/main/doc/cla.md'
          branch: 'cla_signs'
          allowlist: weblate,bot*
          create-file-commit-message: '[CLA] Creating file for storing CLA Signatures'
          signed-commit-message: '[CLA] $contributorName has signed the CLA'
