name: i18n Parser

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  parser:
    uses: HyperPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '20'
      pkg_manager: 'yarn'
      install: 'yarn install --immutable --frozen-lockfile'
      name: 'parser'
      command_one: 'yarn i18n --fail-on-update'
      command_one_name: 'i18n parser'
      checkout_recursive: true
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
      pat: ${{ secrets.pat }}
